#!/bin/bash

python -m torch.distributed.launch \
        --nproc_per_node 1 \
        main_finetune.py \
        --cfg configs/swin_base__800ep/simmim_finetune__swin_base__img224_window7__800ep.yaml \
        --batch-size 128 \
        --data-path /data/work/dataset/imagenet_100cls \
        --pretrained simmim_finetune__swin_base__img224_window7__800ep.pth
